# Project information

site_name: AWS 環境における脅威検知と対応
site_short_name: Scaling threat detection
site_description: 'このワークショップは、AWS セキュリティサービスを理解し、そのサービスを使用して貴社環境の脅威を識別および修復する方法を学習する手助けとなるように設計されています。Amazon GuardDuty、Amazon Macie、Amazon Inspector、AWS Security Hub などのサービスを使用します。これらのサービスを使用して、攻撃中および攻撃後の脅威を調査し、通知と修復パイプラインを設定し、追加的な保護策を講じて、貴社環境のセキュリティを改善する方法を学習します。'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://scaling-threat-detection.awssecworkshops.jp/'

# Repository
repo_name: 'aws-samples/aws-scaling-threat-detection-workshop-jp'
repo_url: 'https://github.com/aws-samples/aws-scaling-threat-detection-workshop-jp'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.jp'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Overview: 'index.md'
  - 'モジュール 1: 環境構築と設定': '01-environment-setup.md'
  - 'モジュール 2: 攻撃シミュレーション': '02-attack-simulation.md'
  - 'モジュール 3: 検知、調査、および対応': '03-detection-and-remediation.md'
  - '# モジュール 4: レビューとディスカッション': '04-review-and-discussion.md'
  - 'コントリビュートのガイドライン': 'contribute.md'